
build:
  image: mcr.microsoft.com/dotnet/sdk:7.0
  stage: build

  script:
    - 'mkdir -p BattleTaskApi/BattleTaskApi/app/build'
    - 'mkdir -p BattleTaskApi/BattleTaskApi/app/publish'
    - 'docker build -t battletask BattleTaskApi/BattleTaskApi/'


deploy:
  stage: deploy
  image: mcr.microsoft.com/dotnet/aspnet:7.0
  script: 
      - 'docker stop battletask || true'
      - 'docker rm attletask || true'
      - 'docker run -p 5000:80 battletask'
  environment: production

