build:
  stage: build

  script:
    - 'ls'
    - 'dotnet --info'
    - 'dotnet build BattleTaskApi/BattleTaskApi.sln'

tests:
  stage: test

  script:
    - 'dotnet test --no-restore'

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production

