
build:
  image: mcr.microsoft.com/dotnet/sdk:7.0
  stage: build

  script:
    - 'ls'
    - 'dotnet --info'
    - 'dotnet build BattleTaskApi/BattleTaskApi.sln -c Debug -o /builds/m2i/battletask/build'
    - 'dotnet publish "/builds/m2i/battletask/BattleTaskApi/BattleTaskApi/BattleTaskApi.csproj" -c Release'
    - 'ls /builds/m2i/battletask/BattleTaskApi/'


deploy:
  stage: deploy
  image: mcr.microsoft.com/dotnet/aspnet:7.0
  script: 
      - 'ls /builds/m2i/battletask/BattleTaskApi/BattleTaskApi/bin/Release/net7.0/publish/'
  environment: production

