build:
  stage: build

  script:
    - 'git clone http://dinogit.fr/m2i/battletask.git'
    - 'dotnet --info'
    - 'dotnet build \BattleTaskApi.sln'

tests:
  stage: test

  script:
    - 'dotnet test --no-restore'

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production

