
build:
  image: mcr.microsoft.com/dotnet/sdk:7.0
  stage: build

  script:
    - 'mkdir -p BattleTaskApi/BattleTaskApi/app/build'
    - 'mkdir -p BattleTaskApi/BattleTaskApi/app/publish'
    - 'docker build -t cmd BattleTaskApi/BattleTaskApi/'


deploy:
  stage: deploy
  image: mcr.microsoft.com/dotnet/aspnet:7.0
  script: 
      - 'ls /builds/m2i/battletask/BattleTaskApi/BattleTaskApi/bin/Release/net7.0/publish/'
  environment: production

