build:
  stage: build

  script:
    - 'ls'
    - 'dotnet --info'
    - 'dotnet build BattleTaskApi/BattleTaskApi.sln'


deploy:
  stage: deploy
  script: 'dotnet publish "BattleTaskApi/BattleTaskApi/BattleTaskApi.csproj"'
  environment: production

