
build:
  image: mcr.microsoft.com/dotnet/sdk:7.0
  stage: build

  script:
    - 'ls'
    - 'dotnet --info'
    - 'dotnet build BattleTaskApi/BattleTaskApi.sln'


deploy:
  stage: deploy
  image: mcr.microsoft.com/dotnet/aspnet:7.0
  script: 
    - 'dotnet publish "BattleTaskApi/BattleTaskApi/BattleTaskApi.csproj"'
    - 'cd /home/deployer/builds/Q1yqx1jQ/0/m2i/battletask/BattleTaskApi/BattleTaskApi/bin/Debug/net7.0/publish/'
    - 'echo Démarrage de lapplication'
    - 'dotnet BattleTaskApi.dll  --urls http://::5000'
    - 'Ces en prod mal poule'
  environment: production

