
build:
  image: mcr.microsoft.com/dotnet/sdk:7.0
  stage: build

  script:
    - 'ls'
    - 'dotnet --info'
    - 'dotnet build BattleTaskApi/BattleTaskApi.sln'
    - 'ls app/build'


deploy:
  stage: deploy
  image: mcr.microsoft.com/dotnet/aspnet:7.0
  script: 
      - 'ls BattleTaskApi/BattleTaskApi'
  environment: production

